services:
  # streamlitapp:
  #   build:
  #     context: ./streamlitapp
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./streamlitapp:/usr/src/app
  #   ports:
  #     - "8501:8501"
  #   # environemnt:
  #   #   -some variable=some value
  my_app:
    build:
      context: ./my_app
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"

  server:
    build:
      context: ./gemini
      dockerfile: docker/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./gemini:/usr/src/app